In [20]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [81]:
y = lambda x: pd.DataFrame(np.where(np.random.rand(x) >0.5,'Head','Tail'))[0].value_counts(normalize=True)
y(22)

Head    0.545455
Tail    0.454545
Name: 0, dtype: float64

In [74]:
df

                                                     0
0            0
0    Head
1    Head
2    Head
3    H...
1            0
0    Tail
1    Head
2    Head
3    H...
2            0
0    Tail
1    Tail
2    Tail
3    H...
3            0
0    Tail
1    Head
2    Head
3    H...
4            0
0    Head
1    Tail
2    Tail
3    H...
..                                                 ...
995          0
0    Tail
1    Head
2    Head
3    T...
996          0
0    Head
1    Head
2    Tail
3    T...
997          0
0    Head
1    Head
2    Tail
3    H...
998          0
0    Tail
1    Head
2    Tail
3    H...
999          0
0    Tail
1    Tail
2    Head
3    H...

[1000 rows x 1 columns]